DROP DATABASE IF EXISTS personacraft;
CREATE DATABASE personacraft;

USE personacraft;

CREATE TABLE users (
	id INT AUTO_INCREMENT PRIMARY KEY,
	email VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	roles VARCHAR(255) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE general (
	id INT AUTO_INCREMENT PRIMARY KEY,
	user_Id INT NOT NULL FOREIGN KEY REFERENCES users(id),
	companyName VARCHAR(255) NOT NULL,
	description VARCHAR(255) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE personal (
	id INT AUTO_INCREMENT PRIMARY KEY,
	user_Id INT NOT NULL FOREIGN KEY REFERENCES users(id),
	first_name VARCHAR(255) NOT NULL,
	last_name VARCHAR(255) NOT NULL,
	street VARCHAR(255) NOT NULL,
	street_add VARCHAR(255) NOT NULL,
	city VARCHAR(255) NOT NULL,
	postal_code VARCHAR(255) NOT NULL,
	country VARCHAR(255) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE account (
	id INT AUTO_INCREMENT PRIMARY KEY,
	user_Id INT NOT NULL FOREIGN KEY REFERENCES users(id),
	login_email VARCHAR(255) NOT NULL FOREIGN KEY REFERENCES users(email),
	login_pwd VARCHAR(255) NOT NULL FOREIGN KEY REFERENCES users(password),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE subscription (
	id INT AUTO_INCREMENT PRIMARY KEY,
	user_Id INT NOT NULL FOREIGN KEY REFERENCES users(id),
	plan VARCHAR(255) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE billing (
	id INT AUTO_INCREMENT PRIMARY KEY,
	user_Id INT NOT NULL FOREIGN KEY REFERENCES users(id),
	billing_email VARCHAR(255) NOT NULL,
	payment_method VARCHAR(255) NOT NULL
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);